<?php

return [
    'SERVICE_KEY' => env('OVERLY_SERVICE_KEY'),
    'PATH_MARKER_CREATE' => env('OVERLY_PATH_MARKER_CREATE'),
    'PATH_MARKER_UPDATE' => env('OVERLY_PATH_MARKER_UPDATE'),
    'PATH_VIDEO_UPLOAD' => env('OVERLY_PATH_VIDEO_UPLOAD'),
    'ALPHA_TYPES' => env('OVERLY_ALPHA_TYPES')
];
